#!/bin/bash
# Shortcuts for livestreamer channels and quality
[ -z "$XDG_CONFIG_HOME" ] &&
XDG_CONFIG_HOME="$HOME/.config"
mkdir -p "$XDG_CONFIG_HOME"
source "$XDG_CONFIG_HOME/rofi-twitch/settings" twitch=http://www.twitch.tv/

# Function to adjust the size and the position
# of the player and the browser using parameters where
# $1 is the application;
# $2 is width; $3 is the height;
# $4 is the x axis; $5 is the y axis
function adjust_window() {
  while ! pidof $1 >> /dev/null ;
  do
    sleep 1
  done
  local WID="$(xdotool search --onlyvisible --sync --class $1 | tail -1)"
  xdotool windowsize $(echo ${WID}) $2 $3 && \
    xdotool windowmove $(echo ${WID}) $4 $5
}

# Some channel names are too long, so you can alias
# your most visited channels, I'm using teamfortresstv
# as an example but you can do as many as you want
case "$1" in
    tftv) channel=teamfortresstv;;
    $1) channel=$1;;
esac

# Choose quality, best by default
case "${2:-b}" in
    b*) quality=best;;
    l*) quality=low;;
    m*) quality=medium;;
    *)
        echo '%s: unkown quality option: %s. Choose one of\n
        [l]ow\n
        [m]edium\n
        [b]est)'"$0" "$2" >&2
        exit 1
        ;;
esac
[ -z "$channel" ] && channel=$(twitchnotifier -c $user -n | perl \
    -MHTML::Entities -pe 'encode_entities($_);' | rofi \
    -theme-str '#window { width: 1000; }' -dmenu -markup-rows -i \
    -p "" | grep -Po '^.+?(?=\is playing)')
[ -z "$channel" ] && exit

# Exec livestreamer
eval streamlink -p \"$player $argument\" --title \"$title\" https://twitch.tv/$channel $quality &
adjust_window $player $playerWidth ${resolution[1]} 0 ${resolution[0]}


# Optionally, you can also launch twitch chat for the channel,
# just add a "&" at the end of the streamlink line and uncomment
# the lines below:

channel="$(echo $channel | tr -d ' ')"
# Conditional statement for chrome/chromium parameters
if [ $browser =  chrome ] || [ $browser = chromium ]
then
  $browser --window-size=$browserWidth,${resolution[1]} --no-default-browser-check --app="https://twitch.tv/popout/$channel/chat" &
fi
# Conditional statement for firefox parameters
# Note that adjust_window() will not work
# if a maximized firefox window is already opened
if [ $browser = firefox ]
then
  $browser -width $browserWidth -height ${resolution[1]} --new-window "https://twitch.tv/popout/$channel/chat" &
fi

adjust_window $browser $browserWidth ${resolution[1]} ${resolution[0]} 0
