#!/bin/bash
user=

# alias most watched channels
case "$1" in
    tftv) channel=teamfortresstv;;
    dist) channel=distortion2;;
    gdq) channel=gamesdonequick;;
    $1) channel=$1;;
esac

# Optionally, you can also launch twitch chat for the channel,
# just add a "&" at the end of the streamlink line and uncomment
# the lines below:

# browser=firefox
# channel="$(echo $channel | tr -d ' ')"
# $browser --new-window "$twitch/popout/$channel/chat"
